export function createGameState({
  makeBoard,
  makeStats,
  loadSave,
  loadMetaProgress,
  makeRunStats,
  createDebugHudState,
  normalizeControlsMap,
  defaultControls,
  defaultTuning,
  playerMaxHp,
  guardMax,
  firstEnemy,
  ultimateDurationMs,
  now = performance.now(),
} = {}) {
  return {
    mode: "start",
    board: makeBoard(),
    bag: [],
    queue: [],
    active: null,
    hold: null,
    canHold: true,
    playerMaxHp,
    playerHp: playerMaxHp,
    guard: 0,
    maxGuard: guardMax,
    runMode: "endless",
    enemyHp: 120,
    enemyMaxHp: 120,
    enemyHpDisplay: 120,
    enemyHpTrail: 120,
    enemyAttackDamage: 8,
    enemyCountdown: 7,
    enemyType: firstEnemy,
    wave: 1,
    defeated: 0,
    dropTimer: 0,
    lockTimer: null,
    lastTime: 0,
    lineFlash: [],
    floaters: [],
    particles: [],
    bursts: [],
    attacks: [],
    pendingHits: [],
    perfectClearFx: null,
    operationReadouts: [],
    combatPopups: [],
    lastDamageBreakdown: null,
    shake: 0,
    enemyHit: 0,
    enemyHitIntensity: 0,
    playerHit: 0,
    heroAnimation: null,
    heroLevelUpFx: null,
    enemyAnimation: null,
    enemyDeathVfx: null,
    placed: 0,
    combo: 0,
    pendingGarbage: 0,
    garbageGrace: 0,
    queueHex: 0,
    mistGarbage: 0,
    lastGarbageHole: null,
    garbageHoleRun: 0,
    miniBoss: false,
    lastClearedBoss: false,
    b2bActive: false,
    b2bChain: 0,
    b2bBrokenFlash: 0,
    lastPerfectClear: false,
    perfectClears: 0,
    ultimateCharge: 0,
    ultimateActive: false,
    ultimateTimer: 0,
    ultimateTimerMax: ultimateDurationMs,
    ultimateSavedBoard: null,
    upgradeMeter: 0,
    nextUpgradeAt: 8,
    upgradeTier: 0,
    upgradeReady: false,
    stats: makeStats(),
    save: loadSave(),
    metaProgress: loadMetaProgress(),
    runStats: makeRunStats(),
    runFinalized: false,
    defeatRenderTraceWarned: false,
    playingStallWarned: false,
    debug: createDebugHudState(),
    challenge: null,
    ascensionRun: null,
    tutorial: null,
    upgradeChoices: [],
    upgradeSelectedIndex: 0,
    upgradeDraftReason: null,
    acquiredRelics: [],
    currentBuildOpen: false,
    upgradePickConfirm: null,
    upgradeMotion: null,
    upgradeDetailOpen: false,
    spinSingularityStacks: 0,
    spinStarterWave: 0,
    spinStarterUses: 0,
    comboConstellationWave: 0,
    comboConstellationFirstUsed: false,
    comboConstellationSecondUsed: false,
    comboSafetyNetWave: 0,
    emergencyRiftShieldWave: 0,
    perfectEchoCharges: 0,
    riftOverdriveCharge: 0,
    lastStarProtocolWave: 0,
    lastStarProtocolReady: false,
    angelWard: 0,
    angelBlessingCharges: 0,
    angelMercyWave: 0,
    devilSinMarks: 0,
    upgrades: {
      tspinBonus: 0,
      garbageCancel: 0,
      comboDelay: 0,
      b2bBonus: 0,
      waveHeal: 0,
      spinBonus: 0,
      allSpinBonus: 0,
      comboDamage: 0,
      defense: 0,
      garbageGrace: 0,
      bossDamage: 0,
      maxHpBonus: 0,
      lineDamage: 0,
      clearHeal: 0,
      spinHeal: 0,
      damageMultiplier: 0,
      guardGain: 0,
      comboGuardGain: 0,
      b2bShield: 0,
      spinGuardStrike: 0,
      comboEchoDamage: 0,
      guardReflect: 0,
      garbageCounterDamage: 0,
      burstCharge: 0,
      perfectBossDelay: 0,
      singularitySpinCore: 0,
      comboConstellation: 0,
      aegisStarMirror: 0,
      garbageAlchemyCore: 0,
      perfectRiftCrown: 0,
      spinStarter: 0,
      b2bCompass: 0,
      comboSafetyNet: 0,
      emergencyRiftShield: 0,
      garbageTransmuter: 0,
      perfectEcho: 0,
      riftOverdrive: 0,
      lastStarProtocol: 0,
      angelHaloSanctuary: 0,
      angelCleansingPrism: 0,
      angelPerfectBenediction: 0,
      devilBloodMoonPact: 0,
      devilAbyssChain: 0,
      devilFallenCrown: 0,
    },
    message: "",
    messageKey: "",
    messageVars: {},
    metaUpgradeMessage: { key: "", vars: {}, until: 0 },
    equipmentUi: {
      view: "inventory",
      filter: "all",
      motion: null,
      message: { key: "", vars: {}, until: 0 },
      selectedOwnedIndex: 0,
    },
    settingsOpen: false,
    settingsTab: "controls",
    pauseView: "menu",
    menuRevealStartedAt: 0,
    mainMenuSelectedIndex: 0,
    bindingAction: null,
    menuSpecialIdleStartedAt: now,
    menuHeroInteraction: {
      hovered: false,
      hoverStartedAt: 0,
      actionKind: "",
      actionStartedAt: 0,
      actionUntil: 0,
      lineKey: "",
      lineKind: "",
      lineStartedAt: 0,
      lineUntil: 0,
      lineIndex: 0,
      idleKind: "cube",
      idleStartedAt: 0,
      idleUntil: 0,
      idleCooldownUntil: 0,
      idleTriggerCount: 0,
    },
    language: "zh",
    controls: normalizeControlsMap(defaultControls),
    tuning: { ...defaultTuning },
    pointer: {
      x: 0,
      y: 0,
      down: false,
      dragging: null,
      elasticSlider: {
        key: "",
        overflow: 0,
        releaseKey: "",
        releaseOverflow: 0,
        releaseStartedAt: 0,
      },
    },
    countdownMs: 0,
    countdownCue: "",
    firstWaveHintMs: 0,
    controlHintsFullUntil: 0,
    bossPhaseBanner: null,
    bossWindup: null,
    lastBossPhase: 1,
    hitStopMs: 0,
    assetLoadingStartedAt: now,
    assetLoadingDone: false,
    lastMoveWasRotate: false,
    lastRotationKind: null,
    lastKickIndex: null,
    input: {
      left: false,
      right: false,
      softDrop: false,
      horizontalDir: 0,
      das: 0,
      arr: 0,
      softDropTimer: 0,
    },
  };
}
